//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 12:27:09 PM MSK 
//


package bankostsch.fns.artefacts.x.root._171_08._4_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import bankostsch.fns.artefacts.x.types._4_0.ФИОТип;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="СвНалРеш">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="ИННФЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННФЛТип"/>
 *                     &lt;element name="ИННЮЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННЮЛТип"/>
 *                     &lt;element name="КИО" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-5"/>
 *                   &lt;/choice>
 *                   &lt;choice>
 *                     &lt;element name="НаимОрг" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-1000"/>
 *                     &lt;element name="ФИО" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ФИОТип"/>
 *                   &lt;/choice>
 *                   &lt;element name="СвДейстРеш" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="НомРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-20" />
 *                           &lt;attribute name="ДатаРеш" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="КодНО" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}СОНОТип" />
 *                           &lt;attribute name="БИКРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
 *                           &lt;attribute name="ДатаВремИнфБД" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="БИК" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
 *                 &lt;attribute name="РезультатЗапр" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-1">
 *                       &lt;enumeration value="0"/>
 *                       &lt;enumeration value="1"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="ДатаВремПолучЗапр" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="КодОбр">
 *           &lt;simpleType>
 *             &lt;restriction base="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-2">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-36" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "\u0441\u0432\u041d\u0430\u043b\u0420\u0435\u0448",
    "\u043a\u043e\u0434\u041e\u0431\u0440"
})
@XmlRootElement(name = "FNSPriostanSchResponse")
public class FNSPriostanSchResponse {

    @XmlElement(name = "\u0421\u0432\u041d\u0430\u043b\u0420\u0435\u0448")
    protected FNSPriostanSchResponse.СвНалРеш свНалРеш;
    @XmlElement(name = "\u041a\u043e\u0434\u041e\u0431\u0440")
    protected String кодОбр;
    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441", required = true)
    protected String идЗапрос;

    /**
     * Gets the value of the свНалРеш property.
     * 
     * @return
     *     possible object is
     *     {@link FNSPriostanSchResponse.СвНалРеш }
     *     
     */
    public FNSPriostanSchResponse.СвНалРеш getСвНалРеш() {
        return свНалРеш;
    }

    /**
     * Sets the value of the свНалРеш property.
     * 
     * @param value
     *     allowed object is
     *     {@link FNSPriostanSchResponse.СвНалРеш }
     *     
     */
    public void setСвНалРеш(FNSPriostanSchResponse.СвНалРеш value) {
        this.свНалРеш = value;
    }

    /**
     * Gets the value of the кодОбр property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКодОбр() {
        return кодОбр;
    }

    /**
     * Sets the value of the кодОбр property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКодОбр(String value) {
        this.кодОбр = value;
    }

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="ИННФЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННФЛТип"/>
     *           &lt;element name="ИННЮЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННЮЛТип"/>
     *           &lt;element name="КИО" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-5"/>
     *         &lt;/choice>
     *         &lt;choice>
     *           &lt;element name="НаимОрг" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-1000"/>
     *           &lt;element name="ФИО" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ФИОТип"/>
     *         &lt;/choice>
     *         &lt;element name="СвДейстРеш" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="НомРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-20" />
     *                 &lt;attribute name="ДатаРеш" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="КодНО" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}СОНОТип" />
     *                 &lt;attribute name="БИКРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
     *                 &lt;attribute name="ДатаВремИнфБД" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="БИК" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
     *       &lt;attribute name="РезультатЗапр" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-1">
     *             &lt;enumeration value="0"/>
     *             &lt;enumeration value="1"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="ДатаВремПолучЗапр" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "\u0438\u043d\u043d\u0444\u043b",
        "\u0438\u043d\u043d\u044e\u043b",
        "\u043a\u0438\u043e",
        "\u043d\u0430\u0438\u043c\u041e\u0440\u0433",
        "\u0444\u0438\u043e",
        "\u0441\u0432\u0414\u0435\u0439\u0441\u0442\u0420\u0435\u0448"
    })
    public static class СвНалРеш {

        @XmlElement(name = "\u0418\u041d\u041d\u0424\u041b")
        protected String иннфл;
        @XmlElement(name = "\u0418\u041d\u041d\u042e\u041b")
        protected String иннюл;
        @XmlElement(name = "\u041a\u0418\u041e")
        protected String кио;
        @XmlElement(name = "\u041d\u0430\u0438\u043c\u041e\u0440\u0433")
        protected String наимОрг;
        @XmlElement(name = "\u0424\u0418\u041e")
        protected ФИОТип фио;
        @XmlElement(name = "\u0421\u0432\u0414\u0435\u0439\u0441\u0442\u0420\u0435\u0448")
        protected List<FNSPriostanSchResponse.СвНалРеш.СвДейстРеш> свДейстРеш;
        @XmlAttribute(name = "\u0411\u0418\u041a", required = true)
        protected String бик;
        @XmlAttribute(name = "\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0417\u0430\u043f\u0440", required = true)
        protected String результатЗапр;
        @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0412\u0440\u0435\u043c\u041f\u043e\u043b\u0443\u0447\u0417\u0430\u043f\u0440", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar датаВремПолучЗапр;

        /**
         * Gets the value of the иннфл property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИННФЛ() {
            return иннфл;
        }

        /**
         * Sets the value of the иннфл property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИННФЛ(String value) {
            this.иннфл = value;
        }

        /**
         * Gets the value of the иннюл property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getИННЮЛ() {
            return иннюл;
        }

        /**
         * Sets the value of the иннюл property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setИННЮЛ(String value) {
            this.иннюл = value;
        }

        /**
         * Gets the value of the кио property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getКИО() {
            return кио;
        }

        /**
         * Sets the value of the кио property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setКИО(String value) {
            this.кио = value;
        }

        /**
         * Gets the value of the наимОрг property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getНаимОрг() {
            return наимОрг;
        }

        /**
         * Sets the value of the наимОрг property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setНаимОрг(String value) {
            this.наимОрг = value;
        }

        /**
         * Gets the value of the фио property.
         * 
         * @return
         *     possible object is
         *     {@link ФИОТип }
         *     
         */
        public ФИОТип getФИО() {
            return фио;
        }

        /**
         * Sets the value of the фио property.
         * 
         * @param value
         *     allowed object is
         *     {@link ФИОТип }
         *     
         */
        public void setФИО(ФИОТип value) {
            this.фио = value;
        }

        /**
         * Gets the value of the свДейстРеш property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the свДейстРеш property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getСвДейстРеш().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FNSPriostanSchResponse.СвНалРеш.СвДейстРеш }
         * 
         * 
         */
        public List<FNSPriostanSchResponse.СвНалРеш.СвДейстРеш> getСвДейстРеш() {
            if (свДейстРеш == null) {
                свДейстРеш = new ArrayList<FNSPriostanSchResponse.СвНалРеш.СвДейстРеш>();
            }
            return this.свДейстРеш;
        }

        /**
         * Gets the value of the бик property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getБИК() {
            return бик;
        }

        /**
         * Sets the value of the бик property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setБИК(String value) {
            this.бик = value;
        }

        /**
         * Gets the value of the результатЗапр property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getРезультатЗапр() {
            return результатЗапр;
        }

        /**
         * Sets the value of the результатЗапр property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setРезультатЗапр(String value) {
            this.результатЗапр = value;
        }

        /**
         * Gets the value of the датаВремПолучЗапр property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getДатаВремПолучЗапр() {
            return датаВремПолучЗапр;
        }

        /**
         * Sets the value of the датаВремПолучЗапр property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setДатаВремПолучЗапр(XMLGregorianCalendar value) {
            this.датаВремПолучЗапр = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="НомРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-20" />
         *       &lt;attribute name="ДатаРеш" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="КодНО" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}СОНОТип" />
         *       &lt;attribute name="БИКРеш" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
         *       &lt;attribute name="ДатаВремИнфБД" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class СвДейстРеш {

            @XmlAttribute(name = "\u041d\u043e\u043c\u0420\u0435\u0448", required = true)
            protected String номРеш;
            @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0420\u0435\u0448", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar датаРеш;
            @XmlAttribute(name = "\u041a\u043e\u0434\u041d\u041e", required = true)
            protected String кодНО;
            @XmlAttribute(name = "\u0411\u0418\u041a\u0420\u0435\u0448", required = true)
            protected String бикРеш;
            @XmlAttribute(name = "\u0414\u0430\u0442\u0430\u0412\u0440\u0435\u043c\u0418\u043d\u0444\u0411\u0414", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar датаВремИнфБД;

            /**
             * Gets the value of the номРеш property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getНомРеш() {
                return номРеш;
            }

            /**
             * Sets the value of the номРеш property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setНомРеш(String value) {
                this.номРеш = value;
            }

            /**
             * Gets the value of the датаРеш property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаРеш() {
                return датаРеш;
            }

            /**
             * Sets the value of the датаРеш property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаРеш(XMLGregorianCalendar value) {
                this.датаРеш = value;
            }

            /**
             * Gets the value of the кодНО property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getКодНО() {
                return кодНО;
            }

            /**
             * Sets the value of the кодНО property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setКодНО(String value) {
                this.кодНО = value;
            }

            /**
             * Gets the value of the бикРеш property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getБИКРеш() {
                return бикРеш;
            }

            /**
             * Sets the value of the бикРеш property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setБИКРеш(String value) {
                this.бикРеш = value;
            }

            /**
             * Gets the value of the датаВремИнфБД property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getДатаВремИнфБД() {
                return датаВремИнфБД;
            }

            /**
             * Sets the value of the датаВремИнфБД property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setДатаВремИнфБД(XMLGregorianCalendar value) {
                this.датаВремИнфБД = value;
            }

        }

    }

}
