//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 12:27:09 PM MSK 
//


package bankostsch.fns.artefacts.x.root._171_08._4_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ИННФЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННФЛТип"/>
 *         &lt;element name="ИННЮЛ" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}ИННЮЛТип"/>
 *         &lt;element name="КИО" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-5"/>
 *       &lt;/choice>
 *       &lt;attribute name="ИдЗапрос" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}string-36" />
 *       &lt;attribute name="БИК" use="required" type="{urn://x-artefacts-fns-bankostsch/types/4.0.1}БИКТип" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "\u0438\u043d\u043d\u0444\u043b",
    "\u0438\u043d\u043d\u044e\u043b",
    "\u043a\u0438\u043e"
})
@XmlRootElement(name = "FNSPriostanSchRequest")
public class FNSPriostanSchRequest {

    @XmlElement(name = "\u0418\u041d\u041d\u0424\u041b")
    protected String иннфл;
    @XmlElement(name = "\u0418\u041d\u041d\u042e\u041b")
    protected String иннюл;
    @XmlElement(name = "\u041a\u0418\u041e")
    protected String кио;
    @XmlAttribute(name = "\u0418\u0434\u0417\u0430\u043f\u0440\u043e\u0441", required = true)
    protected String идЗапрос;
    @XmlAttribute(name = "\u0411\u0418\u041a", required = true)
    protected String бик;

    /**
     * Gets the value of the иннфл property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИННФЛ() {
        return иннфл;
    }

    /**
     * Sets the value of the иннфл property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИННФЛ(String value) {
        this.иннфл = value;
    }

    /**
     * Gets the value of the иннюл property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИННЮЛ() {
        return иннюл;
    }

    /**
     * Sets the value of the иннюл property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИННЮЛ(String value) {
        this.иннюл = value;
    }

    /**
     * Gets the value of the кио property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getКИО() {
        return кио;
    }

    /**
     * Sets the value of the кио property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setКИО(String value) {
        this.кио = value;
    }

    /**
     * Gets the value of the идЗапрос property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getИдЗапрос() {
        return идЗапрос;
    }

    /**
     * Sets the value of the идЗапрос property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setИдЗапрос(String value) {
        this.идЗапрос = value;
    }

    /**
     * Gets the value of the бик property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getБИК() {
        return бик;
    }

    /**
     * Sets the value of the бик property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setБИК(String value) {
        this.бик = value;
    }

}
