//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 12:27:09 PM MSK 
//


package bankostsch.fns.artefacts.x.root._171_08._4_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bankostsch.fns.artefacts.x.root._171_08._4_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bankostsch.fns.artefacts.x.root._171_08._4_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FNSPriostanSchResponse }
     * 
     */
    public FNSPriostanSchResponse createFNSPriostanSchResponse() {
        return new FNSPriostanSchResponse();
    }

    /**
     * Create an instance of {@link FNSPriostanSchResponse.СвНалРеш }
     * 
     */
    public FNSPriostanSchResponse.СвНалРеш createFNSPriostanSchResponseСвНалРеш() {
        return new FNSPriostanSchResponse.СвНалРеш();
    }

    /**
     * Create an instance of {@link FNSPriostanSchRequest }
     * 
     */
    public FNSPriostanSchRequest createFNSPriostanSchRequest() {
        return new FNSPriostanSchRequest();
    }

    /**
     * Create an instance of {@link FNSPriostanSchResponse.СвНалРеш.СвДейстРеш }
     * 
     */
    public FNSPriostanSchResponse.СвНалРеш.СвДейстРеш createFNSPriostanSchResponseСвНалРешСвДейстРеш() {
        return new FNSPriostanSchResponse.СвНалРеш.СвДейстРеш();
    }

}
