//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.19 at 12:27:09 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn://x-artefacts-fns-bankostsch/root/171-08/4.0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bankostsch.fns.artefacts.x.root._171_08._4_0;
